project:
  type: node 
  config:
    buildScript: build
    startScript: start

provider:
  type: aws
  config:
    dev:
      host: YOUR-EC2-INSTANCE-IP
      user: ubuntu
      keyPath: ~/.ssh/your-key.pem
      appPath: /home/ubuntu/your-nextjs-app

environment: dev

steps:
  - lint
  - build
  - deploy

env:
  NODE_ENV: production
  AWS_REGION: us-east-1
  REDIS_URL: ${REDIS_URL}
  DATABASE_URL: ${DATABASE_URL}