name: CI/CD Pipeline

on:
  workflow_call:
    inputs:
      config-path:
        description: 'Path to the config file'
        required: true
        default: 'config.yml'
        type: string
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'dev'
        type: string
      AWS_REGION:
        description: 'AWS Region'
        required: false
        default: 'us-east-1'
        type: string
    secrets:
      inherit: true

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run CI/CD Pipeline
        run: |
          echo "Running CI/CD with config: $CONFIG_PATH and env: $DEPLOY_ENV"
          echo "Available environment variables:"
          env | grep -E '^(REDIS_URL|DATABASE_URL|NODE_ENV|PORT)' || echo "No specific env vars found"
          npm start -- $CONFIG_PATH $DEPLOY_ENV
        env:
          NODE_ENV: production
          CONFIG_PATH: ${{ inputs.config-path }}
          DEPLOY_ENV: ${{ inputs.environment }}
