name: Modular CI/CD

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run CI/CD Pipeline
        run: |
          echo "Running CI/CD with config: ${{ inputs.config-path }} and env: ${{ inputs.environment }}"
          npm start -- ${{ inputs.config-path }} ${{ inputs.environment }}
        env:
          NODE_ENV: production
          CONFIG_PATH: ${{ inputs.config-path }}
          DEPLOY_ENV: ${{ inputs.environment }}
