name: Modular CI/CD

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      REDIS_URL:
        required: false
      DATABASE_URL:
        required: false
      NODE_ENV:
        required: false
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      - name: Run Modular CI/CD Pipeline
        run: |
          echo "Running CI/CD with config: ${{ inputs.config-path }} and env: ${{ inputs.environment }}"
          env | sort
          npx ts-node src/cli.ts ${{ inputs.config-path }} ${{ inputs.environment }}
        env:
          CONFIG_PATH: ${{ inputs.config-path }}
          DEPLOY_ENV: ${{ inputs.environment }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
